spring:
  application:
    name: vector-repository
  profiles:
    include:
      - es
      - api
      - prompt
      - redis
      - log
      - fileupload

  lifecycle:
    timeout-per-shutdown-phase: 5s

server:
  port: 8080
  shutdown: GRACEFUL
